apiVersion: broker.amq.io/v2alpha4
kind: ActiveMQArtemis
metadata:
  name: spring-amq
spec:
  version: 7.8.1
  deploymentPlan:
    size: 1
    image: placeholder
    requireLogin: false
  upgrades:
    enabled: false
---
apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemisAddress
metadata:
  name: spring-amq-fruits
spec:
  addressName: fruits
  queueName: fruits
  routingType: anycast
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: amq-http-console
  labels:
    ActiveMQArtemis: spring-amq
    application: spring-amq-app
spec:
  to:
    kind: Service
    name: spring-amq-hdls-svc
  port:
    targetPort: console-jolokia