ssh root@host01 'git clone https://github.com/fatherlinux/intro-katacoda.git'
ssh root@host01 'ln -s ~/intro-katacoda/subsystems/container-internals-lab-4/assets ~/assets'
ssh root@host01 'git clone https://github.com/fatherlinux/container-supply-chain.git ~/assets/exercise-01-a/'
ssh root@host01 'cd ~/assets/exercise-01-a/; git checkout centos7'
ssh root@host01 'git clone https://github.com/fatherlinux/wordpress-demo.git ~/assets/exercise-01-b/'
ssh root@host01 'cd ~/assets/exercise-01-b/; git checkout lab04-exercise01'
ssh root@host01 '~/assets/exercise-01-b/create-pv.sh'
ssh root@host01 'sed -i s/wpfrontend-wordpress.apps.example.com/`hostname`/ ~/assets/exercise-01-b/wordpress-objects.yaml'
ssh root@host01 'yum install -y links httpd-tools'
ssh root@host01 '/var/lib/openshift/openshift admin policy add-cluster-role-to-user cluster-admin admin'
# ssh root@host01 'cp container-internals-lab-3/exercise-01/mega-proc.sh /usr/bin/mega-proc.sh'
ssh root@host01 'docker pull rhel7'
ssh root@host01 'docker pull rhel7-atomic'
ssh root@host01 'docker pull nate/dockviz'

