ssh root@host01 "for i in {1..200}; do oc project openshift && break || sleep 2; done"
ssh root@host01 "oc create -f /opt/amq-broker-71-basic.yaml -n openshift"
ssh root@host01 "oc create -f /opt/amq-7-image-streams.json -n openshift"
ssh root@host01 "curl -k --silent --location https://rpm.nodesource.com/setup_8.x | sudo bash -"
ssh root@host01 "yum -y install nodejs npm"