ssh root@host01 "mkdir -p /root/projects/quarkus"
ssh root@host01 "touch /etc/rhsm/ca/redhat-uep.pem"
ssh root@host01 "yum -y install openssl openssl-pkcs11"
ssh roor@host01 "touch /root/projects/quarkus/test.txt"
ssh root@host01 "echo -w\ \"\n\" >> ~/.curlrc"